version: '3'

services:
    app:        
        build:
            args:
                user: agusk
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: hellolaravel
        container_name: app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./hellolaravel:/var/www
        networks:
            - webapp-network
        
    webserver:
        image: nginx:alpine
        container_name: webserver
        restart: unless-stopped
        ports:
          - 8080:80
        volumes:
          - ./hellolaravel:/var/www
          - ./nginx:/etc/nginx/conf.d/
        networks:
          - webapp-network
        depends_on:
            - app
            

networks:
    webapp-network:
        driver: bridge
